Reduce ambiguous paths in macros
denoland/deno_core pull request #458
Opened 2024-01-19 09:46 UTC by H1rono

Current macros are not hygienic in path resolution. This causes compile error with codes like below.

```rust
deno_core::extension!(
    ext,
    js = [ "/path/to/ext.js" ]
);

mod std {}
```

error diagnostic:

```
error[E0433]: failed to resolve: could not find `borrow` in `std`
  --> src/lib.rs:14:1
   |
14 | / deno_core::extension!(
15 | |     ext,
16 | |     js = [ "/path/to/ext.js" ],
17 | | );
   | |_^ could not find `borrow` in `std`
   |
   = note: this error originates in the macro `deno_core::extension` (in Nightly builds, run with -Z macro-backtrace for more info)
```

This PR almost resolves this problem, by using unambiguous paths. There are still ambiguous paths remaining, but they won't couse such a issue because they only appear in unexported macros. I'm sorry if I missed something :pray:

references about hygienic macro:

- https://en.wikipedia.org/wiki/Hygienic_macro
- https://doc.rust-lang.org/reference/macros-by-example.html#hygiene
- https://gist.github.com/Kestrer/8c05ebd4e0e9347eb05f265dfb7252e1

2024-01-19 16:55 UTC, mmastrac requested changes
Thanks for the PR -- for unexported macros, I prefer to keep the hygiene to a minimum for readability purposes.

Can we revert everything outside of `extension!`, `external!`, `include_ascii_string!`, `located_script_name!` and `resources.rs`?

2024-01-20 01:34 UTC, H1rono commented
OK, I'll revert other macros.

2024-01-20 03:27 UTC, mmastrac approved these changes
LGTM, thanks! 

@H1rono did you have some way to automatically expand the macro paths, or was this done by hand?

2024-01-20 04:08 UTC, H1rono commented
By hand, unfortunately... I think [cargo-expand](https://github.com/dtolnay/cargo-expand) might be useful for automatic expanding.

2024-01-20 04:27 UTC, merged