ci: only run test-valigrind on main
denoland/deno_core pull request #997
Opened 2024-12-09 16:49 UTC by bartlomieju

2024-12-09 16:51 UTC, dsherret commented
An issue is that this still runs an XL runner, which costs a bit of money each time I think:https://github.com/denoland/deno_core/actions/runs/12240311256/job/34142831809?pr=997

2024-12-16 12:09 UTC, littledivy approved these changes

2024-12-16 14:17 UTC, dsherret requested changes
Is there a way we can get this to not run an xl runner?

2025-01-03 22:34 UTC, bartlomieju commented
@dsherret I changed it to always use a regular runner. I think it's okay if valgrind runs for an hour on `main` branch.

2025-01-04 00:46 UTC, dsherret approved these changes
LGTM

2025-01-04 01:28 UTC, merged